// Thai text for UI strings written inline in the arcade game components
// (start screens, HUD chips, canvas-drawn labels, end screens) shared by
// apps/student-liff and apps/tutor-pwa. Keep this file identical in both apps.
//
// Components call tx("English source", params): the English text is the key
// (gettext style), so the source stays readable and a missing entry still
// renders the English. {param} placeholders are interpolated.
// gameText.test.ts fails when a component renders English that is not routed
// through tx() or when a tx() string has no entry here.
//
// Players are Thai children: keep it short and friendly. HUD chips are small,
// so HUD words stay one or two words.

import { interpolateGameLabel, type GameLabelParams } from "./gameLabels"

export const GAME_TEXT_TH: Record<string, string> = {
  // --- Shared HUD / end screens -------------------------------------------
  "(You)": "(คุณ)",
  Accuracy: "ความแม่นยำ",
  Actions: "คำสั่ง",
  "Action input": "เลือกคำสั่ง",
  "Awaiting Command": "รอคำสั่ง",
  "Battle Log": "บันทึกการต่อสู้",
  "Latest actions": "การกระทำล่าสุด",
  "No actions yet.": "ยังไม่มีการกระทำ",
  "Be the first to play!": "มาเป็นคนแรกที่เล่นกันเลย!",
  "Be the first to set a score!": "มาทำคะแนนเป็นคนแรกกันเลย!",
  Candidate: "ผู้ท้าชิง",
  COMBO: "คอมโบ",
  "Combo: {combo}": "คอมโบ: {combo}",
  Complete: "เสร็จแล้ว",
  "Process finalized.": "เล่นจบแล้ว",
  Correct: "ตอบถูก",
  Difficulty: "ระดับ",
  "Difficulty:": "ระดับ:",
  Easy: "ง่าย",
  Normal: "ปกติ",
  Medium: "ปานกลาง",
  Hard: "ยาก",
  Extreme: "สุดโหด",
  Failure: "ไม่สำเร็จ",
  "System offline.": "ลองใหม่อีกครั้งนะ",
  "GAME OVER": "จบเกม",
  "Hall of Records": "ทำเนียบคะแนน",
  Leaderboard: "ตารางอันดับ",
  "View Leaderboard": "ดูอันดับ",
  "No rankings available.": "ยังไม่มีอันดับ",
  "No rankings yet for this difficulty.": "ระดับนี้ยังไม่มีอันดับ",
  "How to Play": "วิธีเล่น",
  "Pro Tip:": "เคล็ดลับ:",
  "Loading Assets": "กำลังโหลด",
  "Loading assets...": "กำลังโหลด...",
  "Retry Loading": "โหลดใหม่",
  "Objectives reached.": "ทำภารกิจสำเร็จ",
  Ready: "พร้อม",
  "Ready (Space)": "พร้อม (Space)",
  Score: "คะแนน",
  "Score:": "คะแนน:",
  "Score: {score}": "คะแนน: {score}",
  "Score: {p0}": "คะแนน: {p0}",
  Time: "เวลา",
  "Time: {gameTime}s": "เวลา: {gameTime} วิ",
  "Time: {timer}s": "เวลา: {timer} วิ",
  "Victory!": "ชนะแล้ว!",
  Wave: "ด่าน",
  "Wave {wave}": "ด่าน {wave}",
  "WAVE {wave}": "ด่าน {wave}",
  "Level {level}": "ด่าน {level}",
  "Level:": "ด่าน:",
  "Level Reached": "ด่านที่ไปถึง",
  HP: "ชีวิต",
  "HP:": "ชีวิต:",
  "HP: {health}": "ชีวิต: {health}",
  "HP: {hp}/{maxHp}": "ชีวิต: {hp}/{maxHp}",
  Health: "พลังชีวิต",
  "Health Left": "พลังชีวิตที่เหลือ",
  "Hearts Left": "หัวใจที่เหลือ",
  "Lives:": "ชีวิต:",
  "Lives: {lives}": "ชีวิต: {lives}",
  "Lives Left": "ชีวิตที่เหลือ",
  "Mana: {mana}": "มานา: {mana}",
  XP: "XP",
  "XP Earned:": "XP ที่ได้:",
  Find: "หาคำแปล",
  "Find:": "หาคำแปล:",
  "Target: {targetWord}": "เป้าหมาย: {targetWord}",
  "Target Translation": "คำแปลเป้าหมาย",
  Translate: "แปล",
  "Type the translation": "พิมพ์คำแปล",
  "Type translation...": "พิมพ์คำแปล...",
  "Type spell...": "พิมพ์คาถา...",
  Step: "ขั้นที่",
  "Tutorial ·": "สอนเล่น ·",
  "Words Collected": "คำที่เก็บได้",
  "Words: {length}/{length1}": "คำ: {length}/{length1}",
  "Sentence Complete!": "ครบประโยคแล้ว!",
  "Sentences Complete": "ประโยคที่ทำได้",
  "Follow the on-screen prompts to complete the challenge.": "ทำตามคำแนะนำบนจอเพื่อผ่านภารกิจ",
  "Run timer": "เวลาที่เหลือ",
  Vocabulary: "คำศัพท์",
  Items: "ไอเทม",
  "No items loaded...": "ยังไม่มีไอเทม...",
  Exit: "ทางออก",
  EXIT: "ทางออก",
  SAFE: "ปลอดภัย",
  ZZZ: "ZZZ",
  "MINI-MAP": "แผนที่",

  "Start Game": "เริ่มเล่น",
  Restart: "เล่นอีกครั้ง",
  "{seconds}s": "{seconds} วิ",
  // --- Controls -------------------------------------------------------------
  Move: "เดิน",
  Select: "เลือก",
  Collect: "เก็บคำ",
  Shoot: "ยิง",
  Fire: "ยิง",
  Cast: "ร่ายเวท",
  Attack: "โจมตี",
  Dash: "พุ่ง",
  Flap: "กระพือปีก",
  Drift: "ไถล",
  Bounce: "เด้ง",
  Rotate: "หมุน",
  "← → Rotate": "← → หมุน",
  "Open Door": "เปิดประตู",
  "Switch Lane": "เปลี่ยนเลน",
  "Left Lane": "เลนซ้าย",
  "Center Lane": "เลนกลาง",
  "Right Lane": "เลนขวา",
  DPad: "ปุ่มทิศทาง",
  "DPad / Arrows": "ปุ่มทิศทาง / ลูกศร",
  "Touch & Drag": "แตะแล้วลาก",
  "Tap / Click": "แตะ / คลิก",
  "Tap Gate": "แตะประตู",
  "Space": "Space",
  "Shift": "Shift",
  "Space / Enter": "Space / Enter",
  "Space / Tap": "Space / แตะ",
  "Space / Tap Center": "Space / แตะตรงกลาง",
  "Space / Tap Window": "Space / แตะหน้าต่าง",
  "Space = Collect": "Space = เก็บคำ",
  "Space = Fire": "Space = ยิง",
  "Space/Tap = Flap": "Space/แตะ = กระพือปีก",
  "A/D = Drift": "A/D = ไถล",
  "A/D or Tap Sides": "A/D หรือแตะด้านข้าง",
  "Arrow Keys / WASD": "ลูกศร / WASD",
  "Arrows / A-D": "ลูกศร / A-D",
  "Arrows / WASD": "ลูกศร / WASD",
  "Arrows/WASD = Move": "ลูกศร/WASD = เดิน",
  "WASD / Arrows": "WASD / ลูกศร",
  "Left/Right Arrows or Swipe": "ลูกศรซ้าย/ขวา หรือปัด",
  "Up Arrow / W": "ลูกศรขึ้น / W",
  "Move to Edges": "ไปที่ขอบ",
  "Auto-fire": "ยิงอัตโนมัติ",
  Shockwave: "คลื่นพลัง",
  "SHOCKWAVE:": "คลื่นพลัง:",
  "🛡️ SHIELD": "🛡️ โล่",

  // --- Devourer Slime -------------------------------------------------------
  "Devourer Slime": "สไลม์จอมกิน",
  "Eat words, grow big, devour knights!": "กินคำ ตัวโตขึ้น แล้วกินอัศวิน!",
  "Move with WASD / Arrow Keys or Virtual D-Pad": "เดินด้วย WASD / ลูกศร หรือปุ่มทิศทาง",
  "Eat word orbs in the correct sentence order": "กินลูกแก้วคำตามลำดับประโยค",
  "Grow bigger to devour enemy knights": "ตัวโตขึ้นเพื่อกินอัศวินศัตรู",
  "START DEVOURING": "เริ่มกินเลย!",

  // --- Abyssal Well -----------------------------------------------------------
  "The Abyssal Well": "บ่อน้ำมรณะ",
  "Defend the Rim": "ป้องกันขอบบ่อ",
  "Enemies climb up from the well carrying word orbs.": "ศัตรูปีนขึ้นมาจากบ่อพร้อมลูกแก้วคำ",
  "Shoot the enemies in the correct sentence order!": "ยิงศัตรูตามลำดับคำในประโยค!",
  "If an enemy reaches the rim, you lose a life. Don't let them through!": "ถ้าศัตรูถึงขอบบ่อจะเสียหนึ่งชีวิต อย่าให้ผ่านไปนะ!",
  "Enter the Well": "ลงบ่อกันเลย",
  "Abyssal Depths": "ก้นบ่อมรณะ",
  "Well Depth:": "ความลึก:",
  "Rotate left/right to aim, tap center to fire. Hit enemies carrying the correct word in sequence!":
    "หมุนซ้าย/ขวาเพื่อเล็ง แตะตรงกลางเพื่อยิง ยิงศัตรูที่ถือคำถูกตามลำดับ!",
  "Shallow Well": "บ่อตื้น",
  "Deep Chasm": "เหวลึก",
  Abyss: "ก้นเหว",

  // --- Dungeon Liberator ------------------------------------------------------
  "Dungeon Liberator": "ปลดปล่อยคุกใต้ดิน",
  "Rescue the Prisoners": "ช่วยนักโทษ",
  "Collect prisoners in the correct word order to build your rescue party.": "ช่วยนักโทษตามลำดับคำเพื่อรวมทีม",
  "Wrong prisoner? They panic and flee. Monster hits your trail? The tail gets cut off!":
    "ช่วยผิดคน เขาจะตกใจวิ่งหนี ถ้ามอนสเตอร์ชนแถว แถวจะขาด!",
  "Guide everyone to the exit portal to complete the sentence and escape!": "พาทุกคนไปที่ประตูทางออกเพื่อหนีให้สำเร็จ!",
  "Enter the Dungeon": "เข้าคุกใต้ดิน",
  "Words Rescued": "คำที่ช่วยได้",
  "Escaped!": "หนีสำเร็จ!",
  "Captured!": "ถูกจับแล้ว!",
  "The dungeon claimed another hero...": "คุกใต้ดินจับฮีโร่ไว้อีกคน...",

  // --- Griffin Rider's Escape -------------------------------------------------
  "Griffin Rider's Escape": "หนีภัยบนหลังกริฟฟิน",
  "Enchanted Forest Runner": "บินผ่านป่ามหัศจรรย์",
  "Swipe left or right to change lanes.": "ปัดซ้ายหรือขวาเพื่อเปลี่ยนเลน",
  "Fly through the gate with the next word in the sentence.": "บินผ่านประตูที่มีคำถัดไปของประโยค",
  "Avoid storm clouds and wrong words to keep your lives!": "หลบเมฆพายุและคำผิดเพื่อรักษาชีวิต!",
  "Take Flight": "ออกบิน",
  "Gryphon Down!": "กริฟฟินตกแล้ว!",
  "The skies were too dangerous today. Retreat and recover.": "วันนี้ท้องฟ้าอันตรายเกินไป พักแล้วลองใหม่นะ",

  // --- Griffin Sky-Joust ------------------------------------------------------
  "Griffin Sky-Joust": "ประลองบนฟ้ากริฟฟิน",
  "Aerial Word Combat": "ศึกคำศัพท์กลางเวหา",
  "Tap to flap wings and gain altitude.": "แตะเพื่อกระพือปีกบินขึ้น",
  "Land ON TOP of enemy knights carrying the target word.": "ลงเหยียบบนหัวอัศวินที่ถือคำเป้าหมาย",
  "Striking from below or hitting the wrong word costs a heart!": "ชนจากด้านล่างหรือชนคำผิดจะเสียหัวใจ!",
  "Use momentum to drift! Screen edges wrap around horizontally.": "ใช้แรงส่งไถลไป! ขอบจอซ้ายขวาทะลุถึงกันได้",
  "Words Joustred": "คำที่ประลองชนะ",
  "Fledgling (Low Gravity)": "มือใหม่ (แรงโน้มถ่วงต่ำ)",
  "Rider (Standard)": "นักขี่ (ปกติ)",
  "Veteran (Heavy Gravity)": "ทหารผ่านศึก (แรงโน้มถ่วงสูง)",

  // --- Gryphon Patrol ---------------------------------------------------------
  "Gryphon Patrol": "ลาดตระเวนกริฟฟิน",
  "Patrol the skies and hunt down the sentence!": "บินลาดตระเวนแล้วตามล่าประโยค!",
  "Fly using Arrow Keys or WASD": "บินด้วยลูกศรหรือ WASD",
  "Shoot using Space to reveal words from enemies": "กด Space ยิงศัตรูเพื่อเปิดคำ",
  "Collect word orbs in the correct sentence order": "เก็บลูกแก้วคำตามลำดับประโยค",
  "START PATROL": "เริ่มลาดตระเวน",
  "Mission Accomplished!": "ภารกิจสำเร็จ!",
  "You've successfully patrolled the skies and decoded the message.": "ลาดตระเวนสำเร็จ และไขข้อความได้แล้ว",

  // --- Haunted Library --------------------------------------------------------
  "The Haunted Library": "ห้องสมุดผีสิง",
  "A Spooky Word Adventure": "ผจญภัยคำศัพท์สุดหลอน",
  "Explore the library floors using the DPad or Arrow Keys.": "สำรวจแต่ละชั้นด้วยปุ่มทิศทางหรือลูกศร",
  "Bounce on the orange trampolines at the edges to reach higher floors.": "เด้งบนแทรมโพลีนสีส้มที่ขอบเพื่อขึ้นชั้นบน",
  "Open doors by pressing UP when nearby to collect the next word.": "กดขึ้นเมื่ออยู่ใกล้ประตูเพื่อเปิดและเก็บคำถัดไป",
  "Avoid ghosts and bats! Slamming a door on a ghost will stun it.": "หลบผีและค้างคาว! ปิดประตูใส่ผีจะทำให้ผีมึน",
  "Collecting words in the correct order is key to purifying the library!": "เก็บคำให้ถูกลำดับเพื่อปัดเป่าห้องสมุด!",
  "Novice Scholarly": "นักอ่านมือใหม่",
  "Master Archivist": "ปรมาจารย์ห้องสมุด",
  "Forbidden Knowledge": "ความรู้ต้องห้าม",

  // --- Labyrinth of the Goblin King --------------------------------------------
  "Labyrinth of the Goblin King": "เขาวงกตราชาก๊อบลิน",
  "Navigate the Maze": "ฝ่าเขาวงกต",
  "Navigate the maze and collect word orbs in the correct order.": "เดินในเขาวงกตแล้วเก็บลูกแก้วคำตามลำดับ",
  "The translation is shown at the top - find the words!": "คำแปลอยู่ด้านบน หาคำให้เจอนะ!",
  "Avoid goblins! Collisions cost lives. Wrong words cost a life.": "หลบก๊อบลิน! ชนหรือเก็บคำผิดจะเสียชีวิต",
  "Collect all words to become a Paladin and defeat the goblins!": "เก็บคำให้ครบเพื่อเป็นอัศวินและปราบก๊อบลิน!",
  "Enter the Labyrinth": "เข้าเขาวงกต",
  "Goblins Eaten": "ก๊อบลินที่ปราบได้",
  "Words: {length}/{length1} | Goblins Eaten: {goblinsEaten}": "คำ: {length}/{length1} | ปราบก๊อบลิน: {goblinsEaten}",
  "Labyrinth Conquered!": "พิชิตเขาวงกตแล้ว!",
  "You defeated the Goblin King!": "ปราบราชาก๊อบลินได้แล้ว!",
  "Lost in the Maze!": "หลงในเขาวงกต!",
  "The goblins were too strong...": "ก๊อบลินเก่งเกินไป...",
  "Small Dungeon": "คุกเล็ก",
  "Medium Dungeon": "คุกกลาง",
  "Large Dungeon": "คุกใหญ่",

  // --- Realm Carver ------------------------------------------------------------
  "Realm Carver": "นักวาดแผนที่",
  "Magical Cartographer": "นักทำแผนที่เวทมนตร์",
  "Move to draw lines and claim territory.": "เดินเพื่อลากเส้นยึดพื้นที่",
  "Enclose words to capture them in order.": "ล้อมคำเพื่อเก็บตามลำดับ",
  "Don't let monsters hit your trail!": "อย่าให้มอนสเตอร์ชนเส้นของเรา!",
  "Return to a claimed area to finish your circuit.": "กลับเข้าพื้นที่ของเราเพื่อปิดวง",
  "Start Mapping": "เริ่มวาดแผนที่",
  "Map Completed!": "วาดแผนที่สำเร็จ!",
  "The realm has been fully mapped.": "วาดแผนที่ครบทั้งดินแดนแล้ว",
  "Cartographer Defeated!": "นักทำแผนที่แพ้แล้ว!",
  "The wild magic was too strong.": "เวทมนตร์ป่าแรงเกินไป",

  // --- Rune Forge Chamber -------------------------------------------------------
  "Rune Forge Chamber": "ห้องตีรูน",
  "Forge the Ancient Runes": "ตีรูนโบราณ",
  "Tap the word circles in the correct order to forge the rune.": "แตะวงกลมคำตามลำดับเพื่อตีรูน",
  "The translation is shown on the central rune stone - find the words!": "คำแปลอยู่บนหินรูนตรงกลาง หาคำให้เจอนะ!",
  "Complete the sentence before the forge cools down. Wrong taps damage the rune!": "ทำประโยคให้เสร็จก่อนเตาเย็น แตะผิดรูนจะเสียหาย!",
  "The target circle glows gold - tap it first! Watch the timer!": "วงกลมเป้าหมายเรืองแสงสีทอง แตะก่อนเลย! ระวังเวลาด้วย",
  "Enter the Forge": "เข้าห้องตีรูน",
  "Levels Forged": "ด่านที่ผ่าน",
  "Words Forged": "คำที่ตีได้",
  "Rune Integrity": "ความแข็งแรงรูน",
  "Rune: {health}%": "รูน: {health}%",
  "Forge: {timer}s": "เตา: {timer} วิ",
  "Rune Shattered!": "รูนแตกแล้ว!",
  "The forge grew too cold... You reached level {level}.": "เตาเย็นแล้ว... ไปได้ถึงด่าน {level}",

  // --- Shadow Gate Dungeon ------------------------------------------------------
  "Shadow Gate Dungeon": "คุกประตูเงา",
  "Escape the Darkness": "หนีจากความมืด",
  "Collect word crystals in the correct order to unlock the exit gate.": "เก็บคริสตัลคำตามลำดับเพื่อเปิดประตูทางออก",
  "The creature patrols a circular path — stay outside its detection ring to avoid being chased.":
    "สัตว์ประหลาดเดินเป็นวงกลม อยู่นอกวงที่มันมองเห็นจะได้ไม่โดนไล่",
  "Avoid the shadow creature! Wrong words and collisions drain your health.": "หลบสัตว์เงา! คำผิดและการชนจะลดพลังชีวิต",
  "The creature turns RED when it spots you. Grab crystals while it patrols away!": "ถ้ามันเห็นเราจะกลายเป็นสีแดง เก็บคริสตัลตอนมันเดินห่างออกไป!",
  "⚠ DETECTED!": "⚠ โดนเห็นแล้ว!",
  "👁 Undetected": "👁 ยังไม่โดนเห็น",
  "You found the way out!": "เจอทางออกแล้ว!",
  "The shadows consumed you...": "ความมืดกลืนเราไปแล้ว...",
  "Dark Cell": "ห้องขังมืด",
  "Forgotten Crypt": "สุสานที่ถูกลืม",
  "Abyssal Chamber": "ห้องใต้ดินลึก",
  "Lazy Guard (Slow)": "ยามขี้เกียจ (ช้า)",
  "Alert Sentry (Medium)": "ยามตื่นตัว (กลาง)",
  "Elite Watchman (Fast)": "ยามหัวกะทิ (เร็ว)",
  "Shadow Demon (Fast)": "ปีศาจเงา (เร็ว)",
  "Guard Type:": "ชนิดยาม:",

  // --- Spellweaver's Run ----------------------------------------------------------
  "Spellweaver's Run": "นักร่ายเวทวิ่งผ่าน",
  "Collect word orbs in the correct order to form the sentence.": "เก็บลูกแก้วคำตามลำดับให้เป็นประโยค",
  "The translation scrolls at the top - use it to find the next word!": "คำแปลเลื่อนอยู่ด้านบน ใช้หาคำถัดไป!",
  "Wrong words drain your mana. Run out of mana and the spell fails!": "คำผิดทำให้มานาลด ถ้ามานาหมดคาถาจะล้มเหลว!",
  "Watch the translation carefully. Tap the lane when the correct orb enters the collection zone!":
    "ดูคำแปลให้ดี แตะเลนเมื่อลูกแก้วที่ถูกเข้ามาในโซนเก็บ!",
  "Begin the Run": "เริ่มวิ่ง",
  "You wove the spell perfectly!": "ร่ายคาถาได้สมบูรณ์!",
  "Mana Depleted!": "มานาหมดแล้ว!",
  "The magic faded away...": "เวทมนตร์จางหายไป...",

  // --- Storm Castle Tower ---------------------------------------------------------
  "Storm the Castle Tower": "บุกหอคอยปราสาท",
  "Scale the Walls": "ปีนกำแพง",
  "Storm the Tower": "บุกหอคอย",
  "Windows on the tower show words from the sentence.": "หน้าต่างบนหอคอยมีคำจากประโยค",
  "Move to windows and tap to collect words in the correct order!": "ไปที่หน้าต่างแล้วแตะเพื่อเก็บคำตามลำดับ!",
  "Dodge boiling oil and falling rocks!": "หลบน้ำมันเดือดและก้อนหินที่ตกลงมา!",
  "Move quickly but carefully. Wrong words slam the window shut and cost a life!": "รีบแต่ต้องระวัง คำผิดหน้าต่างจะปิดและเสียหนึ่งชีวิต!",
  "Tower Height:": "ความสูงหอคอย:",
  "Squire's Tower (4 words)": "หอคอยเด็กฝึก (4 คำ)",
  "Knight's Keep (5 words)": "ป้อมอัศวิน (5 คำ)",
  "Lord's Citadel (6 words)": "ปราสาทท่านลอร์ด (6 คำ)",
  "Wall Breached!": "ปีนสำเร็จ!",

  // --- Village Guardian -----------------------------------------------------------
  "Village Guardian": "ผู้พิทักษ์หมู่บ้าน",
  "Defend the Village": "ปกป้องหมู่บ้าน",
  "Rescue villagers with word bubbles in the correct order to form the sentence.": "ช่วยชาวบ้านที่ถือคำตามลำดับให้เป็นประโยค",
  "Avoid monsters! Collisions lose villagers. Wrong words add time penalty.": "หลบมอนสเตอร์! ชนแล้วชาวบ้านจะหาย คำผิดจะโดนหักเวลา",
  "The target villager glows gold! Lead all rescued villagers to the sanctuary to win!": "ชาวบ้านเป้าหมายเรืองแสงสีทอง! พาทุกคนไปที่ปลอดภัยเพื่อชนะ!",
  "Defend the Innocent": "ปกป้องชาวบ้าน",
  "Levels Survived": "ด่านที่รอด",
  "Villagers Saved": "ชาวบ้านที่ช่วยได้",
  "Rescued:": "ช่วยได้:",
  "Village Overrun!": "หมู่บ้านแตกแล้ว!",
  "The monsters were too strong... You reached level {level}.": "มอนสเตอร์เก่งเกินไป... ไปได้ถึงด่าน {level}",
  "Opponent:": "คู่ต่อสู้:",
  Opponent: "คู่ต่อสู้",
  "Bandits (Wander)": "โจร (เดินเตร็ดเตร่)",
  "Goblins (Chase)": "ก๊อบลิน (ไล่ตาม)",
  "Dragons (Hunt)": "มังกร (ล่า)",
  "Scout Party": "หน่วยสอดแนม",
  "War Band": "กองทัพเล็ก",
  "Full Siege": "บุกเต็มกำลัง",
  Apocalypse: "วันสิ้นโลก",

  // --- Archer's Revenge -------------------------------------------------------------
  "Archer's Revenge": "การล้างแค้นของนักธนู",
  "Draw Your Bow": "ง้างธนู",
  "Target word is shown at the top. Find the enemy with the matching translation.": "คำเป้าหมายอยู่ด้านบน หาศัตรูที่ถือคำแปลที่ตรงกัน",
  "Tap a column to fire an arrow. Only the enemy with their SHIELD DOWN is vulnerable.": "แตะคอลัมน์เพื่อยิงธนู ยิงได้เฉพาะศัตรูที่ลดโล่ลง",
  "Don't hit shielded enemies! They will shoot back and damage your HP.": "อย่ายิงศัตรูที่ยกโล่! เขาจะยิงกลับและลดชีวิต",
  "Champion Archer!": "สุดยอดนักธนู!",
  "Overwhelmed!": "สู้ไม่ไหวแล้ว!",

  // --- Paladin's Twin-Soul ------------------------------------------------------------
  "Paladin's Twin-Soul": "อัศวินวิญญาณคู่",
  "Gargoyle Defense": "ป้องกันการ์กอยล์",
  "Move left/right to defend against gargoyles.": "เดินซ้าย/ขวาเพื่อป้องกันการ์กอยล์",
  "Rescue your twin soul from the correct enemy.": "ช่วยวิญญาณคู่จากศัตรูที่ถูกตัว",
  "Match the translation to identify your ally!": "จับคู่คำแปลเพื่อหาเพื่อนของเรา!",
  "Double your fire rate by rescuing your soul mate!": "ช่วยวิญญาณคู่ได้ จะยิงเร็วขึ้นสองเท่า!",
  "The gargoyles have been repelled.": "ไล่การ์กอยล์ไปได้แล้ว",
  "The twin souls have been lost.": "วิญญาณคู่หายไปแล้ว",
  "Defense Successful!": "ป้องกันสำเร็จ!",
  "Realm Overrun!": "ดินแดนแตกแล้ว!",

  // --- Wizard vs Zombie ---------------------------------------------------------------
  "Wizard vs Zombie": "พ่อมดปะทะซอมบี้",
  "Arcane Defense": "เวทป้องกัน",
  "The horde is endless. Survive as long as possible by collecting Healing Orbs.": "ซอมบี้มาไม่หยุด เก็บลูกแก้วรักษาเพื่ออยู่รอดให้นานที่สุด",
  "Match the Target Word shown at the bottom to heal (+10 HP).": "เก็บคำแปลของคำเป้าหมายด้านล่างเพื่อฟื้นชีวิต (+10)",
  "Each correct orb grants one Shockwave charge. Use it to blast zombies back!": "ลูกแก้วที่ถูกให้คลื่นพลัง 1 ครั้ง ใช้ผลักซอมบี้ออกไป!",
  "Use Shockwave when surrounded to create space for an escape!": "โดนล้อมเมื่อไหร่ ใช้คลื่นพลังเปิดทางหนี!",
  "The target changes every few seconds. Keep an eye on the top text!": "คำเป้าหมายเปลี่ยนทุกไม่กี่วินาที คอยดูด้านบนนะ!",
  "Defend the Realm": "ปกป้องดินแดน",

  // --- Dragon Flight / Dragon Rider -----------------------------------------------------
  "Dragon Flight": "บินกับมังกร",
  "Dragon Flight Tutorial": "สอนเล่นบินกับมังกร",
  "Soar through magical gates to complete the sentence!": "บินผ่านประตูเวทเพื่อทำประโยคให้ครบ!",
  Dragon: "มังกร",
  "Shadow Dragon (Fast)": "มังกรเงา (เร็ว)",
  "⚔️ Big Boss Battle! ⚔️": "⚔️ สู้กับบอสใหญ่! ⚔️",

  // --- Enchanted Library ----------------------------------------------------------------
  "My Grimoire": "สมุดคาถาของฉัน",
  "Initializing Grimoire...": "กำลังเปิดสมุดคาถา...",
  "Collect all words twice!": "เก็บทุกคำให้ได้สองครั้ง!",

  // --- Potion Rush ----------------------------------------------------------------------
  HOLD: "พัก",
  TRASH: "ถังขยะ",
  "DONE!": "เสร็จ!",
  "RUINED!": "พังแล้ว!",

  // --- Rune Match -----------------------------------------------------------------------
  "POWER WORD": "คำพลัง",
  SKILLS: "สกิล",
  "MATCHES {correctAnswers}/{targetMatches}": "จับคู่ {correctAnswers}/{targetMatches}",
  "SELECTED RUNE": "รูนที่เลือก",
  "WRONG PAIR": "คู่ไม่ถูก",
  "RESHUFFLE!": "สลับใหม่!",
  "Picking the Wrong Orb reshuffles the field and costs 5 points.": "เลือกผิดจะสลับกระดานและเสีย 5 คะแนน",
  "Goblin:": "ก๊อบลิน:",
  Goblin: "ก๊อบลิน",
  Skeleton: "โครงกระดูก",
  Orc: "ออร์ค",
  "Weak but fast.": "อ่อนแอแต่ว่องไว",
  "Restless undead.": "ผีดิบไม่ยอมหลับ",
  "A fierce warrior.": "นักรบดุดัน",
  "The ultimate challenge.": "ด่านท้าทายที่สุด",
  "Select a monster to begin the rune match battle.": "เลือกมอนสเตอร์เพื่อเริ่มจับคู่รูน",
  "Rune Type:": "ชนิดรูน:",
  "Common Stone": "หินธรรมดา",
  "Rare Crystal": "คริสตัลหายาก",
  "Void Essence": "แก่นแห่งความว่างเปล่า",
  "💡 HINT!": "💡 คำใบ้!",
  "✨ Ultimate!": "✨ ท่าไม้ตาย!",
  "💥 ATTACK! -100 HP": "💥 โจมตี! -100",
  "🔥 COMBO x{currentStreak}": "🔥 คอมโบ x{currentStreak}",
  "Cave Spider (Medium)": "แมงมุมถ้ำ (กลาง)",
  "Goblin Scout (Slow)": "ก๊อบลินสอดแนม (ช้า)",
  "Orc Hunter (Medium)": "นักล่าออร์ค (กลาง)",
  "Enemy Type:": "ชนิดศัตรู:",
  Power: "พลัง",

  Shuffle: "สลับ",
  Bomb: "ระเบิด",
  Freeze: "แช่แข็ง",
  Hint: "คำใบ้",
  "BLOCKED!": "กันได้!",
  "HURRY!": "เร็วเข้า!",
  "SHUFFLE!": "สลับแล้ว!",
  "FROZEN!": "แช่แข็ง!",
  "SHIELD!": "โล่!",
  "POWER!": "พลัง!",
  "COMBO x{count}!": "คอมโบ x{count}!",
  Male: "ชาย",
  Female: "หญิง",
  "Forest Clearing": "ลานกลางป่า",
  "Ruined Road": "ถนนร้าง",
  "Magic Arena": "สนามเวทมนตร์",
  "Throne Hall": "ท้องพระโรง",
  Slime: "สไลม์",
  Spectre: "วิญญาณ",
  Elemental: "ภูตธาตุ",
  // --- RPG Battle -------------------------------------------------------------------------
  "RPG Battle": "ศึกคำศัพท์",
  Battle: "ต่อสู้",
  Basic: "พื้นฐาน",
  Reward: "รางวัล",
  "Choose a location": "เลือกสถานที่",
  "Choose an enemy": "เลือกศัตรู",
  "Choose your hero": "เลือกฮีโร่",
  "Choose Your Opponent": "เลือกคู่ต่อสู้",
  "Background only.": "เปลี่ยนแค่ฉากหลัง",
  "Cosmetic choice only.": "เปลี่ยนแค่หน้าตา",
  "Stronger foes grant more XP.": "ศัตรูเก่งกว่าได้ XP มากกว่า",
  "{label} - {xpMultiplier}x XP": "{label} - XP คูณ {xpMultiplier}",
  "{label} enemy": "ศัตรู {label}",
  "{label} hero": "ฮีโร่ {label}",
  "Elite (Hunt)": "หัวกะทิ (ล่า)",
  "Scout (Patrol)": "หน่วยสอดแนม (ลาดตระเวน)",
  "Warrior (Chase)": "นักรบ (ไล่ตาม)",
  "Enemy sprite sheet": "ภาพศัตรู",
  "Player sprite sheet": "ภาพผู้เล่น",

  "Begin Defense": "เริ่มป้องกัน",
  "Read the Thai translation at the top to figure out which word comes next. Monsters get faster each level!":
    "อ่านคำแปลภาษาไทยด้านบนเพื่อหาคำถัดไป มอนสเตอร์จะเร็วขึ้นทุกด่าน!",
  "The monsters have overrun the defense.": "มอนสเตอร์บุกผ่านแนวป้องกันไปแล้ว",
  "The realm is safe... for now.": "ดินแดนปลอดภัยแล้ว... ในตอนนี้",
  "The target orb glows gold! During Heroic Aura, goblins flee and you can eat them for bonus XP!":
    "ลูกแก้วเป้าหมายเรืองแสงสีทอง! ตอนมีออร่าฮีโร่ ก๊อบลินจะหนี และปราบได้รับ XP เพิ่ม!",
  "Use the translation banner at the top to plan your route.": "ดูคำแปลด้านบนเพื่อวางแผนเส้นทาง",
  // --- Magic Defense -------------------------------------------------------------------------
  "Magic Defense": "เวทป้องกันปราสาท",
}

/** Translate an inline UI string (English source text) to Thai, interpolating {params}. */
export function tx(source: string, params?: GameLabelParams): string {
  const value = Object.prototype.hasOwnProperty.call(GAME_TEXT_TH, source) ? GAME_TEXT_TH[source] : source
  return interpolateGameLabel(value, params)
}
