import { PrismaClient } from "@prisma/client";
import * as fs from "fs";
import * as path from "path";

const prisma = new PrismaClient();

async function main() {
  console.log("🚀 Starting data insertion from JSON...");

  // Resolve file paths
  const bookJsonPath = path.resolve(__dirname, "book.json");
  const seriesJsonPath = path.resolve(__dirname, "series.json");
  const articleJsonPath = path.resolve(__dirname, "article.json");

  if (!fs.existsSync(bookJsonPath) || !fs.existsSync(seriesJsonPath) || !fs.existsSync(articleJsonPath)) {
    console.error("❌ Error: One or more JSON files are missing in the packages/database folder.");
    return;
  }

  const bookData = JSON.parse(fs.readFileSync(bookJsonPath, "utf-8")); // This maps to 'Series'
  const seriesData = JSON.parse(fs.readFileSync(seriesJsonPath, "utf-8")); // This maps to 'Book'
  const articleData = JSON.parse(fs.readFileSync(articleJsonPath, "utf-8")); // Maps to 'Article'

  // 1. Seed Series (from book.json)
  console.log("📦 Step 1: Upserting Series...");
  const seriesMap = new Map<string, string>(); // Store seriesId lookup map

  for (const s of bookData) {
    const series = await prisma.series.upsert({
      where: { code: s.code },
      update: {
        name: s.name,
        cefrLevel: s.cefrLevel,
        raLevelStart: s.raLevelStart,
        raLevelEnd: s.raLevelEnd,
        tagline: s.tagline,
      },
      create: {
        code: s.code,
        name: s.name,
        cefrLevel: s.cefrLevel,
        raLevelStart: s.raLevelStart,
        raLevelEnd: s.raLevelEnd,
        tagline: s.tagline,
        // Let Prisma / Postgres automatically generate a new UUID for seriesId
      },
    });
    seriesMap.set(s.code, series.seriesId);
    console.log(`✅ Series: [${s.code}] id=${series.seriesId}`);
  }

  // 2. Seed Books (from series.json)
  console.log("\n📖 Step 2: Upserting Books...");
  const bookMap = new Map<string, string>(); // Maps title -> bookId

  for (const b of seriesData) {
    // Normalize placeholder: "UUID_FOR_ORIGINS" -> "ORIGINS"
    const seriesCode = b.seriesId.replace(/^UUID_FOR_/, "");
    const mappedSeriesId = seriesMap.get(seriesCode);
    
    if (!mappedSeriesId) {
      console.warn(`⚠️ Skipped book ${b.bookCode} because Series "${seriesCode}" was not found.`);
      continue;
    }

    const book = await prisma.book.upsert({
      where: { bookCode: b.bookCode },
      update: {
        seriesId: mappedSeriesId,
        levelNumber: b.levelNumber,
        title: b.title,
        articleCount: b.articleCount,
        classHours: b.classHours,
        independentHours: b.independentHours,
      },
      create: {
        bookCode: b.bookCode,
        seriesId: mappedSeriesId,
        levelNumber: b.levelNumber,
        title: b.title,
        articleCount: b.articleCount,
        classHours: b.classHours,
        independentHours: b.independentHours,
        // Let Prisma generate the new bookId uuid
      },
    });
    bookMap.set(b.title, book.bookId);
    console.log(`✅ Book: [${b.bookCode}] - Title: "${b.title}" id=${book.bookId}`);
  }

  // 3. Seed Articles (from article.json)
  console.log("\n📰 Step 3: Upserting Articles...");
  let totalArticles = 0;
  for (const [bookTitle, articles] of Object.entries(articleData)) {
    const bookId = bookMap.get(bookTitle);
    
    if (!bookId) {
      console.warn(`⚠️ Skipped processing articles for unknown book title: "${bookTitle}"`);
      continue;
    }
    
    const articleArray = articles as any[];
    console.log(`🔹 Processing ${articleArray.length} articles for "${bookTitle}"...`);

    for (const art of articleArray) {
      const cleanArticleId = art.articleId;
      if (!cleanArticleId) continue;

      // Note: using combined unique index generated by Prisma
      await prisma.article.upsert({
        where: {
          articleId_bookId: {
            articleId: cleanArticleId,
            bookId: bookId,
          }
        },
        update: {
          title: art.title,
          type: art.type,
          genre: art.genre,
        },
        create: {
          articleId: cleanArticleId,
          bookId: bookId,
          title: art.title,
          type: art.type,
          genre: art.genre,
        }
      });
      totalArticles++;
    }
  }
  
  console.log(`\n✨ Success! Ingested ${bookMap.size} books and ${totalArticles} articles total.`);
}

main()
  .catch((e) => {
    console.error("❌ Execution failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
