import { PrismaClient } from "@prisma/client";
import * as fs from "fs";
import * as path from "path";

const prisma = new PrismaClient();

// book.json shape (generated by src/build-book-json.js):
// {
//   series: { [seriesName]: { cefrLevel, raLevelStart, raLevelEnd, tagline,
//                             plannedBooks, classHoursTotal, independentHoursTotal } },
//   books:  { [bookKey]: [{ type, genre, title, id }] }
// }
interface SeriesMeta {
  cefrLevel: string;
  raLevelStart: number;
  raLevelEnd: number;
  tagline: string;
  plannedBooks: number;
  classHoursTotal: number;
  independentHoursTotal: number;
}

interface BookArticle {
  type?: string;
  genre?: string;
  title: string;
  id: string;
}

function toReadingCourseName(bookKey: string) {
  const match = bookKey.match(/([0-9]+(?:\.[0-9]+)?)/);
  return match ? `Reading ${match[1]}` : bookKey;
}

function getLevelNumber(bookKey: string) {
  const match = bookKey.match(/([0-9]+)/);
  return match ? parseInt(match[1]) : 1;
}

async function main() {
  console.log("🚀 Starting book import...");

  const bookJsonPath = path.resolve(__dirname, "../book.json");
  if (!fs.existsSync(bookJsonPath)) {
    console.error(`❌ Error: book.json not found at ${bookJsonPath}`);
    return;
  }
  const data = JSON.parse(fs.readFileSync(bookJsonPath, "utf-8")) as {
    series: Record<string, SeriesMeta>;
    books: Record<string, BookArticle[]>;
  };

  // Safety guard: this script only builds an EMPTY catalog. It must never
  // wipe live data — abort if any series/books already exist.
  const existingSeries = await prisma.series.count();
  const existingBooks = await prisma.book.count();
  if (existingSeries > 0 || existingBooks > 0) {
    console.error(
      `❌ Catalog is not empty (series=${existingSeries}, books=${existingBooks}). ` +
        "Aborting to avoid duplicating or clobbering data.",
    );
    process.exit(1);
  }

  for (const [seriesName, meta] of Object.entries(data.series)) {
    console.log(`📦 Creating series: ${seriesName}`);
    const series = await prisma.series.create({
      data: {
        code: seriesName,
        name: seriesName,
        cefrLevel: meta.cefrLevel,
        raLevelStart: meta.raLevelStart,
        raLevelEnd: meta.raLevelEnd,
        tagline: meta.tagline,
      },
    });

    // Per-book hours come from the series totals spread over the planned book count
    const classHours = Math.round(meta.classHoursTotal / meta.plannedBooks);
    const independentHours = Math.round(meta.independentHoursTotal / meta.plannedBooks);

    for (const [bookKey, jsonArticles] of Object.entries(data.books)) {
      const levelNumber = getLevelNumber(bookKey);
      if (levelNumber < meta.raLevelStart || levelNumber > meta.raLevelEnd) continue;

      // De-duplicate within the same book
      const seenIds = new Set<string>();
      const uniqueArticles = jsonArticles.filter((a) => {
        if (!a.id || seenIds.has(a.id)) return false;
        seenIds.add(a.id);
        return true;
      });

      // Level number = first number in the book key ("Reading 3.1" -> 3)
      const courseName = toReadingCourseName(bookKey);

      console.log(`📖 Adding book: ${bookKey} (Articles: ${uniqueArticles.length})`);

      const book = await prisma.book.create({
        data: {
          seriesId: series.seriesId,
          bookCode: courseName,
          title: courseName,
          levelNumber,
          articleCount: uniqueArticles.length,
          classHours,
          independentHours,
        },
      });

      if (uniqueArticles.length > 0) {
        await prisma.article.createMany({
          data: uniqueArticles.map((a) => ({
            articleId: a.id,
            bookId: book.bookId,
            title: a.title,
            type: a.type,
            genre: a.genre,
          })),
        });
      }
    }
  }

  console.log("✅ Import complete!");
}

main()
  .catch((e) => {
    console.error("❌ Import failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
